name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run with Node v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm
        run: |
          npm install --global npm@7
      - name: Versions
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
      - run: npm ci
      - name: Build & Package
        run: |
          rm -rf dist
          npm run build
          npm run package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
      - name: Upload Chrome Webstore
        run: |
          npx chrome-webstore-upload-cli upload --source extension.zip
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
