name: reviewdog

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run with Node v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm
        run: |
          npm install --global npm@7
      - name: Versions
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
      - run: npm ci
      - name: reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: '--ext .ts ./src'
